apiVersion: v1
kind: Service
metadata:
  name: notification-worker-service
  namespace: default
spec:
  selector:
    app: notification-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # Standard port if we added health check endpoints
  type: ClusterIP
